import { useEffect, useState, useMemo } from 'react';
import { Loader2, AlertTriangle, FileText, ArrowRight, ShieldCheck, User } from 'lucide-react';
import { fetchInvestigations } from '../services/api';
import { SeverityBadge } from '../components/ui/severity-badge';
import { SEVERITY_LEVELS } from '../lib/severity';

const LOADING = { status: 'loading', data: [] };

/**
 * The Investigation History surface — "what investigations have already occurred?"
 * Formatted as an authoritative Investigation Register / Ledger.
 */
export default function InvestigationHistory({ onOpenInvestigation }) {
  const [state, setState] = useState(LOADING);
  const [severityFilter, setSeverityFilter] = useState('ALL');

  useEffect(() => {
    let cancelled = false;
    setState(LOADING);
    fetchInvestigations({ limit: 50 })
      .then(data => { if (!cancelled) setState({ status: 'success', data }); })
      .catch(() => { if (!cancelled) setState({ status: 'error', data: [] }); });
    return () => { cancelled = true; };
  }, []);

  const rows = useMemo(() => {
    const sorted = [...state.data].sort((a, b) => new Date(b.created_at) - new Date(a.created_at));
    if (severityFilter === 'ALL') return sorted;
    return sorted.filter(r => r.severity === severityFilter);
  }, [state.data, severityFilter]);

  return (
    <div className="h-full flex flex-col gap-5 max-w-[1400px] mx-auto pb-8">
      {/* Editorial Register Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-border pb-3">
        <div>
          <div className="flex items-center gap-2">
            <FileText className="w-4 h-4 text-brand-ember" aria-hidden="true" />
            <h1 className="text-sm font-bold uppercase tracking-wider text-text-primary">
              Investigation Register
            </h1>
          </div>
          <p className="text-xs text-text-secondary mt-0.5">
            Historical forensic dossier ledger generated by the behavioral anomaly engine
          </p>
        </div>

        {/* Filter Controls */}
        <div className="flex items-center gap-3">
          <label className="flex items-center gap-2 text-xs text-text-muted font-medium">
            <span>Filter Severity:</span>
            <select
              className="bg-surface border border-border text-xs text-text-primary rounded-md px-2.5 py-1 outline-none focus-visible:ring-2 focus-visible:ring-focus font-medium"
              value={severityFilter}
              onChange={e => setSeverityFilter(e.target.value)}
            >
              <option value="ALL">All Severities</option>
              {SEVERITY_LEVELS.map(level => (
                <option key={level} value={level}>{level}</option>
              ))}
            </select>
          </label>
          <span className="text-[11px] font-mono text-text-muted bg-surface-soft px-2 py-0.5 rounded border border-border">
            {rows.length} Record{rows.length === 1 ? '' : 's'}
          </span>
        </div>
      </div>

      {/* Main Register Body */}
      <div className="flex-1 min-h-0 overflow-y-auto bg-surface border border-border rounded-lg shadow-xs">
        {state.status === 'loading' && (
          <div className="flex items-center justify-center h-48 text-text-muted text-xs gap-2" role="status">
            <Loader2 className="w-4 h-4 animate-spin text-brand-ember" aria-hidden="true" />
            <span>Loading forensic investigation ledger…</span>
          </div>
        )}

        {state.status === 'error' && (
          <div className="flex items-center justify-center h-48 text-sev-critical-text text-xs gap-2 p-6 text-center" role="alert">
            <AlertTriangle className="w-4 h-4 text-sev-critical-indicator shrink-0" aria-hidden="true" />
            <span>Failed to load investigation history from gateway.</span>
          </div>
        )}

        {state.status === 'success' && rows.length === 0 && (
          <div className="flex flex-col items-center justify-center h-48 text-text-muted text-xs p-6 text-center">
            <ShieldCheck className="w-6 h-6 mb-2 text-text-muted/60" aria-hidden="true" />
            <span>No investigation dossiers recorded matching active filter.</span>
          </div>
        )}

        {state.status === 'success' && rows.length > 0 && (
          <ul className="divide-y divide-border">
            {rows.map(inv => (
              <li key={inv.investigation_id}>
                <button
                  type="button"
                  onClick={() => onOpenInvestigation(inv.event_id, 'history')}
                  className="w-full text-left p-4 flex items-center justify-between gap-5 hover:bg-surface-elevated transition-colors outline-none focus-visible:ring-2 focus-visible:ring-focus group"
                >
                  <div className="min-w-0 flex-1">
                    {/* User, Target Event ID, and Timestamp */}
                    <div className="flex items-center gap-2.5 flex-wrap mb-1">
                      <span className="w-5 h-5 rounded bg-surface-soft border border-border flex items-center justify-center text-text-secondary">
                        <User className="w-3 h-3" />
                      </span>
                      <span className="text-xs font-bold text-text-primary tracking-tight">
                        {inv.user_id}
                      </span>
                      <span className="text-[11px] text-text-muted font-mono bg-surface-soft px-1.5 py-0.2 rounded border border-border">
                        EVT-{inv.event_id}
                      </span>
                      <span className="text-[10px] text-text-muted font-mono">
                        {new Date(inv.created_at).toUTCString()}
                      </span>
                    </div>

                    {/* Summary narrative */}
                    {inv.summary && (
                      <p className="text-xs text-text-secondary line-clamp-1 mt-0.5 font-normal">
                        {inv.summary}
                      </p>
                    )}
                  </div>

                  {/* Severity Badge & Open Action */}
                  <div className="flex items-center gap-4 shrink-0">
                    <SeverityBadge severity={inv.severity} showScore score={inv.risk_score} />
                    <span className="text-xs text-text-muted group-hover:text-brand-ember flex items-center gap-1 transition-colors font-medium">
                      Inspect <ArrowRight className="w-3.5 h-3.5" />
                    </span>
                  </div>
                </button>
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
}
